version: '3.8'

services:
  frontend:
    build: ./web
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
